---
dir:
  out: test/data/method
  prep: test/data/method/prep
experiments:
  - sample: Test1
    ref: test/data/GRCh37.fa
    #intervals: test/data/target-regions.bed
    calls:
      - name: gatk
        metadata:
          aligner: novoalign
          caller: gatk
          technology: illumina
        file: test/data/gatk-calls.vcf
        align: test/data/aligned-reads.bam
        remove-refcalls: true
        normalize: false
        annotate: true
      - name: freebayes
        metadata:
          aligner: novoalign
          caller: freebayes
          technology: illumina
        file: test/data/freebayes-calls.vcf
        align: test/data/aligned-reads.bam
        annotate: true
        filters:
          - HRun > 5.0
          - QD < 2.0
          - FS > 60.0
          - MQRankSum < -12.5
      - name: cg
        metadata:
          aligner: cg
          caller: cg
          technology: cg
        prep: true
        fix-sample-header: true
        file: test/data/cg-calls.vcf
    finalize:
      - method: multiple
        target: gatk
      - method: recal-filter
        target: [gatk, freebayes]
        params:
          filters: [HRun > 5.0]
          classifiers: [AD, DP, QUAL, PL, gms_illumina]
          xspecific: true
          trusted:
            total: 0.75
            technology: 0.65
      - method: validate
        target: gatk
        params:
          filters:
            keep: [QD < 10.0]
            validate: [QD > 10.0]
          validate:
            approach: random
            count: 1
            top-metric:
              - name: "QD"
                mod: -1
