---
dir:
  out: test/data/method
  prep: test/data/method/prep
experiments:
  - sample: Test1
    ref: test/data/GRCh37.fa
    intervals: test/data/target-regions.bed
    calls:
      - name: gatk
        file: test/data/gatk-calls.vcf
        align: test/data/aligned-reads.bam
        refcalls: false
        normalize: false
        annotate: true
      - name: freebayes
        file: test/data/freebayes-calls.vcf
        align: test/data/aligned-reads.bam
        annotate: true
        filters:
          - HRun > 5.0
          - QD < 2.0
          - FS > 60.0
          - MQRankSum < -12.5
      - name: cg
        prep: true
        file: test/data/cg-calls.vcf
    finalize:
      - method: multiple
        target: gatk
      - method: recal-filter
        target: [gatk, freebayes]
        params:
          #annotations:  [QD, HaplotypeScore, MQRankSum, ReadPosRankSum, FS, MQ, DP, AB]
          filters: [HRun > 5.0]
      # - method: validate
      #   target: gatk
      #   params:
      #     validate-count: 10
      #     validate-approach: top
        
