---
dir:
  out: test/data/method
  prep: test/data/method/prep
experiments:
  - sample: Test1
    ref: test/data/GRCh37.fa
    intervals: test/data/target-regions.bed
    align: test/data/aligned-reads.bam
    calls:
      - name: gatk
        file: test/data/gatk-calls.vcf
        refcalls: false
        normalize: false
        annotate: true
      - name: freebayes
        file: test/data/freebayes-calls.vcf
        annotate: true
        filters:
          - HRun > 5.0
          - QD < 2.0
          - FS > 60.0
          - MQRankSum < -12.5
    finalize:
      - method: recal-filter
        target: [gatk, freebayes]
        params:
          #annotations:  [QD, HaplotypeScore, MQRankSum, ReadPosRankSum, FS, MQ, DP, AB]
          filters: [HRun > 5.0]
