---
dir:
  out: test/data/grading
  prep: test/data/grading/prep
experiments:
  - sample: NA00001
    ref: test/data/GRCh37.fa
    intervals: test/data/phasing-reference-regions.bed
    summary-level: quick
    calls:
      - name: reference
        file: test/data/phasing-reference.vcf
      - name: contestant
        prep: true
        file: test/data/phasing-contestant.vcf
        intervals: test/data/phasing-contestant-regions.bed
