---
# Configureation information for running web front-end to run scoring on
# sequencing inputs

ref:
  - sample: NA00001
    description: Test Genome
    genome: test/data/GRCh37.fa
    genome-alts: []
    variants: test/data/phasing-reference.vcf
    intervals: test/data/phasing-reference-regions.bed
    default-compare: test/data/phasing-contestant.vcf

params:
  subsample:
    method: k-means
    count: 10000

remote:
  public:
    - /Home/Public/chapmanb/xprize
  biodata: /Home/Public/chapmanb/biodata

dir:
  html-root: "public"
  cache: "tmp/cache"
  work: "tmp"
  template: "template"
